version: "3.9"
services:
  cache-writer:
    container_name: cache-writer
    build: .
    volumes:
      - ./example:/home/gradle
  cache-reader:
    container_name: cache-reader
    build: .
    volumes:
      - ./example:/home/gradle
