name = "gradle-ipfs-build-cache"

[defaults]
  builder = "docker:generic"
  runner = "local:docker"

[builders."docker:generic"]
  enabled = true

[runners."local:docker"]
  enabled = true
  exposed_ports = { pprof = "6060", go_rpc = "1234",  ipfs_swarm = "4001", ipfs_api = "5001", ipfs_gateway = "8080", ipfs_websocket = "8081" }

[[testcases]]
  name = "from-cache"
  instances = { min = 2, max = 2, default = 2 }
