name = "gradle-ipfs-build-cache"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[builders."docker:generic".build_args]
source_directory = "plan"

[runners."local:docker"]
enabled = true

[[testcases]]
name = "from-cache"
instances = { min = 2, max = 2, default = 2 }
