/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package caching.ipfs

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'caching.ipfs.greeting' plugin.
 */
class IpfsBuildCachePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("caching.ipfs.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
