name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: .github/scripts/install-ipfs.sh
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan
